name: Build and deploy to Github Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm install && npm install @rollup/rollup-linux-x64-gnu
        # @rollup/rollup-linux-x64-gnu is needed for Github Actions https://github.com/vitejs/vite/discussions/15532#discussioncomment-8527272

      - name: Compile Svelte
        run: npm run build

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./public"

  deploy-pages:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: production
      url: ${{ steps.pages.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: pages
        uses: actions/deploy-pages@v4
